# Site
repository: Ranjith002/resume
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ranjith Ramachandran
# title: Your job title
email: mail@ranjithramachandran.com
# email_title: Email (Email title override)
# phone: +61 424 031 817
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: ranjithr02
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-0000000"
gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/LinkedIn5.png
about_content: | # this will include new lines to allow paragraphs
  Technology Enthusiast with over 13+ years of experience in technical development, infrastructure and cloud solutions, ERP implementations and upgrades, vendor and project management, IT-business engagement and stakeholder management

content:
  
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Reserve Bank of Australia (RBA)
        sub_title: Technical Lead
        caption: July 2021 - present
        # link: Link to company (optional)
        # quote: >
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Led and performed ERP (PeopleSoft) upgrade and infrastructure refresh at the Bank
          - Deliver roadmaps and strategies for keeping technology current and aligned to business
          - Led critical incident management attaining business awards for excellence from C-suite
          - Maintain the currency and availability of applications as per SLAs
          - Participate in disaster recovery exercises and develop remediation outcomes
          - Work closely with Business on requirements to deliver outcome based solutions
          - Proactively engage vendors to ensure product delivery within agreed timelines and costs
          - Assist developers, review code, and implement CI/CD pipelines for deployment to Production
          - Aid transformation project to Workday with requirements analysis, design, and delivery of products
          - Prepare network diagrams, operating procedures and solution architecture design documents
          - Enable application monitoring through integration with the ELK stack
        
      - layout: left
        title: Australian National University (ANU)
        sub_title: Technical Consultant (ERP/Database)
        caption: Sep 2019 - Jun 2021
        # link: Link to company (optional)
        # quote: >
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Performed ERP (PeopleSoft) upgrades across Finance, Campus Solutions and HCM systems
          - Architected and built resilient database clusters and VMs for the university’s top tier systems
          - Designed a security data masking solution for PII (Personally Identifiable Information)
          - Implemented automation processes that improved efficiency by 95% for Business users
          - Led the application of regulatory updates for Payroll and Student data
          - Proactively engaged with business, infrastructure and development teams for issue resolution
          - Helped implement CI/CD pipelines with focus on governance and auditing requirements
          - Delivered efficiency improvements to performance, integrations and testing frameworks
          
      - layout: left
        title: Presence of IT (acquired by Deloitte)
        sub_title: Technical Consultant/Lead
        caption: Jul 2016 - Sep 2019
        # link: Link to company (optional)
        # quote: >
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Designed, implemented, upgraded and supported ERP (PeopleSoft) systems for multiple clients
          - Designed Production and non-Production architecture for infrastructure deployment 
          - Led discovery exercises into emerging Chatbots platforms on ERP systems
          - Designed and delivered lift and shift of application from on premise to Cloud
          - Evaluated customer environments and assess impact on the current processes and data
          - Worked with Cloud vendors on infra and analyse usage reporting for cost optimisation
          - Led discovery work for early adopter projects on nationwide payroll reporting
          - Presented on innovation and early adoption of Cloud products, nationally and internationally,
            <br>including at OOW, San Francisco
          - Effectively led and supported team members to ensure timely delivery for multiple clients.
          - Trained users on sysadmin activities and patching methods as part of BAU
       
      - layout: left
        title: University of New South Wales (UNSW)
        sub_title: Upgrade Specialist
        caption: Jul 2015 - Sep 2016
        # link: Link to company (optional)
        # quote: >
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Conducted requirements analysis, engaged with business and performed the <br>upgrade/transformation activities for legacy ERP (PeopleSoft) end to end
          - Administered Unix and Windows systems for application and database activities
          - Performed the Release Management activities as per project requirements
          - Utilised shell scripts for automating process handling for application and web servers
          - Tuned data conversion programs and performed database maintenance activities
      
      - layout: left
        title: Infosys
        sub_title: Sysadmin/Technology Analyst
        caption: Nov 2009 - Jun 2015
        # link: Link to company (optional)
        # quote: >
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Created, configured ERP(PeopleSoft) servers for multiple clients and supported upgrades
          - Designed and implemented security solutions for projects, developed and tested programs <br> to
            automate user profile creation for a large US retail giant
          - Prepared training materials and trained teams on business support initiatives
          - Trained users and team members in Security and Administration activities
          - Integrated applications with external portals and resolved integration issues
          - Performed fit-gap analysis and designed the technical architecture for upgrades
          - Improved system performance post upgrades and handled data migrations
          
          
  - title: Education
    layout: list
    content:
      - layout: center
        title: Amrita School of Engineering
        sub_title: Bachelor of Technology
        caption: 2005 - 2009  
        #quote: >
          #Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
         # Description of qualification
         
         
#  - title: Skills
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

#     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
